apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "etcd-cloud-operator.fullname" . }}
spec:
  minAvailable: 60%
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "etcd-cloud-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
