---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ include "etcd-cloud-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "etcd-cloud-operator.name" . }}
    helm.sh/chart: {{ include "etcd-cloud-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - "get"
    - "list"
- apiGroups:
  - "apps"
  resources:
  - statefulsets
  verbs:
  - "get"
  - "list"
  resourceNames:
  - {{ include "etcd-cloud-operator.fullname" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "etcd-cloud-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "etcd-cloud-operator.name" . }}
    helm.sh/chart: {{ include "etcd-cloud-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "etcd-cloud-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "etcd-cloud-operator.name" . }}
    helm.sh/chart: {{ include "etcd-cloud-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "etcd-cloud-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "etcd-cloud-operator.fullname" . }}
